import Head from 'next/head'
import Navbar from './Navbar'
import { Slide, VStack, useDisclosure, Text, Button, Box, Stack, HStack, Heading } from '@chakra-ui/react'
import Footer from '../components/Footer'

const Layout = ({ Component, pageProps, props }) => {
	// If a page will export a static property 'title' it will be added to the website title
	const { title } = pageProps
	let combined_title = `The Mosh`
	if (title) combined_title += ` - ${title}`

	const { isOpen, onToggle } = useDisclosure({ defaultIsOpen: true })
	return (
		<VStack
		>
			<Head>
				<title>{combined_title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Component {...pageProps} />

			<Slide direction='bottom' in={isOpen} style={{ zIndex: 10 }}>
				
				<Stack
					p='20px'
					color='white'
					mt='4'
					bg='gray.800'
					rounded='md'
					shadow='md'
					direction={{base:'column', md:'row'}}
				>
					<Text fontWeight={'bold'} as='h1'>Cookie Policy</Text>

					
					<Text>
					
						This website stores data such as cookies to enable essential site functionality, as well as marketing, personalization, and analytics. You may decline this banner to continue with only essential cookies.
					</Text>
					<Stack justify={'flex-end'} py={4} direction={{base:'column',md:'row'}}>
					<Button bgColor={'gray.100'} py={2} color="black" _hover={{background:'gray.300', color:'black'}} onClick={onToggle}>Got It!</Button>
					</Stack>

				</Stack>
			</Slide>
			<Footer />
		</VStack>
	)
}

export default Layout